production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOSTNAME'] %>
  pool: 5

development:
  adapter: postgresql
  database: h2o_dev
  pool: 5

test:
  adapter: postgresql
  database: h2o_test
  pool: 5
